### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by markjsc** [lumamontes/expo-router-auth#1]
Luma - thank you for sharing this example!

I'm new to using Expo Router and found the [official Authentication example](https://docs.expo.dev/router/reference/authentication/) very confusing!

Your example solved all of the problems and gave me the understanding I needed to move forward.

Thank you!! 👏

Mark Johnston
Owensboro, KY (USA)

**Comment by lumamontes** [comment]
Hey Mark, i'm glad to hear this example was helpful! I'm always happy to help. Have a great day! 😊
